# Generated by Django 5.1.6 on 2025-05-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_downloads'),
    ]

    operations = [
        migrations.AddField(
            model_name='welcomenote',
            name='image',
            field=models.ImageField(default=None, max_length=200, upload_to='images/'),
        ),
    ]
