# Generated by Django 5.1.6 on 2025-05-17 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_welcomenote_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='welcomenote',
            name='image',
        ),
    ]
