# Generated by Django 5.1.6 on 2025-05-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_remove_welcomenote_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='welcomenote',
            name='image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='images/'),
        ),
    ]
