# Generated by Django 5.1.6 on 2025-05-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_welcomenote_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='objective',
            name='image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='vision',
            name='image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='whoarewe',
            name='image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='images/'),
        ),
    ]
