# Generated by Django 5.1.6 on 2025-06-19 19:43

import django.db.models.deletion
import tkinter.tix
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_mission_image_objective_image_vision_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('mobile_number', models.CharField(max_length=13)),
                ('id_number', models.CharField(max_length=200)),
                ('name_of_the_organization', models.CharField(max_length=200)),
                ('number_of_year_of_experience_in_emobility_sector', models.IntegerField()),
                ('registration_fee', models.CharField(choices=[('Tsh.5,000', 'Tsh.5,000')], max_length=20)),
                ('annual_membership_subscription', models.CharField(choices=[('Tsh.10,000 1 Year', 'Tsh.10,000 1 Year'), ('Tsh.20,000 2 Year', 'Tsh.20,000 2 Year'), ('Tsh.30,000 3 Year', 'Tsh.30,000 3 Year')], max_length=20)),
                ('describe_your_contribution', models.TextField()),
                ('what_are_the_individual_expectations', models.TextField()),
                ('i_agree', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=20)),
                ('introduce', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=20)),
                ('area_of_specialization', models.ForeignKey(blank=tkinter.tix.Tree, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.specialization')),
            ],
        ),
    ]
