# Generated by Django 5.1.6 on 2025-07-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_specialization_individual'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('mobile_number', models.CharField(max_length=13)),
                ('address', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Electric Bicycles', 'Electric Bicycles'), ('Electric Motorcycles', 'Electric Motorcycles'), ('Electric Tuktuks/3 Wheelers', 'Electric Tuktuks/3 Wheelers'), ('Electric 4 Wheeler-Passenger', 'Electric 4 Wheeler-Passenger'), ('Electric 4 Wheeler- Commercial vehicles(Trucks, Vans, etc)', 'Electric 4 Wheeler- Commercial vehicles(Trucks, Vans, etc)'), ('Electric 4 Wheeler- Buses', 'Electric 4 Wheeler- Buses'), ('Electric 4 Wheeler - Specialized equipment', 'Electric 4 Wheeler - Specialized equipment')], max_length=200)),
                ('number_of_existing_employees', models.IntegerField()),
                ('name_of_the_organization_representative', models.CharField(max_length=200)),
                ('email_the_representative', models.EmailField(max_length=200)),
                ('mobile_number_of_representative', models.CharField(max_length=13)),
                ('describe_the_motivation_to_join_the_association', models.TextField()),
                ('what_are_the_organization_expectations_once_you_join_the_association', models.TextField()),
                ('upload_Company_Profile', models.FileField(upload_to='images/')),
                ('membership_Category', models.CharField(choices=[('E-Mobility Company', 'E-Mobility Company'), ('Associate/Affiliate Member', 'Associate/Affiliate Member'), ('Support Organisation', 'Support Organisation')], max_length=200)),
                ('terms_and_constitution_of_the_organization', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=200)),
            ],
        ),
    ]
