# Generated by Django 5.1.6 on 2025-07-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='organization',
            name='category',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='membership_Category',
        ),
        migrations.AddField(
            model_name='organization',
            name='category',
            field=models.ManyToManyField(to='mainapp.categorymodel'),
        ),
        migrations.AddField(
            model_name='organization',
            name='membership_Category',
            field=models.ManyToManyField(to='mainapp.categorymembership'),
        ),
    ]
