# Generated by Django 5.1.6 on 2025-10-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_categorymembership_categorymodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefit',
            name='image',
            field=models.ImageField(blank=True, default='', max_length=200, null=True, upload_to='images/'),
        ),
    ]
