# Generated by Django 5.1.6 on 2025-10-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_teammember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='annual_membership_subscription',
            field=models.CharField(choices=[('Tsh.0 1 Year', 'Tsh.0 1 Year'), ('Tsh.0 2 Year', 'Tsh.0 2 Year'), ('Tsh.0 3 Year', 'Tsh.0 3 Year')], max_length=20),
        ),
        migrations.AlterField(
            model_name='individual',
            name='id_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='individual',
            name='registration_fee',
            field=models.CharField(choices=[('Tsh.0', 'Tsh.0')], max_length=20),
        ),
    ]
