# Generated by Django 5.1.6 on 2025-10-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_alter_individual_annual_membership_subscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='annual_membership_subscription',
            field=models.CharField(choices=[('Tsh.0 1 Year', 'Tsh.0 1 Year'), ('Tsh.0 2 Year', 'Tsh.0 2 Year')], max_length=20),
        ),
    ]
